# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZTlhYzhjNDhiNGNiMjY3ZDg1ZjA3NDY2ZmY0MzkzNWJmMmZhY2U0ZTI5ZDQyMDQxMmQ1MjBjMzMwNDBhMWEzMGJhNjNmYWM1NWZmZTVmNDMxNzNlYmE0YzYzODVlNWE0MzczMTNmYTNjNzVmNTJiNTlkYmQ5NmE5MzVmMDYzNDc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
